// A TLS client over UbiqOS's sockets -- see ubiqos_tls.h.
//
// mbedTLS does the protocol; this file is what it needs from the machine and
// does not find on its own: bytes in and out through the kernel's lwIP
// sockets, the time for certificate dates, and entropy for keys.
//
// The sockets never block. A send with no room answers 0 and a receive with
// nothing yet answers 0, which mbedTLS knows as WANT_WRITE and WANT_READ; the
// waiting is done here, in this process, by sleeping between tries -- the same
// shape as fetch and ping, and the right way round: the stack runs in the USB
// task and may not wait for anybody.

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "ubiqos_abi.h"
#include "ubiqos_tls.h"

#include "mbedtls/ssl.h"
#include "mbedtls/entropy.h"
#include "mbedtls/ctr_drbg.h"
#include "mbedtls/x509_crt.h"
#include "mbedtls/error.h"
#include "mbedtls/platform.h"
#include "mbedtls/platform_time.h"

// The built-in roots, one DER certificate after another. Generated by
// tools/make_roots.py; the list and the fingerprints are in that file.
extern const uint8_t  ubiqos_tls_roots[];
extern const uint32_t ubiqos_tls_roots_len;

#define EXTRA_ROOTS   "/sd/certs.pem"
#define SPIN_MS       5
#define CONNECT_MS    10000
#define HANDSHAKE_MS  20000

// mbedTLS's own code for a failed send, which it only defines with NET_C.
#define ERR_SEND_FAILED  -0x004E

struct ubiqos_tls {
    int32_t                  sock;
    mbedtls_ssl_context      ssl;
    mbedtls_ssl_config       conf;
    mbedtls_x509_crt         ca;
    mbedtls_entropy_context  entropy;
    mbedtls_ctr_drbg_context drbg;
};

// --- time -------------------------------------------------------------------
//
// newlib's time() here counts from boot, which is right for timing things and
// wrong for a certificate that is valid from one date to another. The wall
// clock is the kernel's, set by SNTP, and /var/utc is how a program reads it.
// Read once when a connection opens and carried forward on the tick, so a
// handshake that looks at the time several times reads the card once.

static uint32_t utc_at_open, ticks_at_open;

static bool read_utc(uint32_t *out)
{
    const int32_t fd = ubiqos_open_flags("/var/utc", UBIQOS_O_RDONLY);
    if (fd < 0) return false;
    char b[16];
    const int32_t n = ubiqos_read(fd, (uint8_t *)b, sizeof b - 1);
    ubiqos_close(fd);
    if (n <= 0) return false;                 // empty: not set yet
    uint32_t v = 0;
    for (int32_t i = 0; i < n && b[i] >= '0' && b[i] <= '9'; i++) v = v * 10 + (uint32_t)(b[i] - '0');
    *out = v;
    return v != 0;
}

static mbedtls_time_t tls_time(mbedtls_time_t *timer)
{
    const mbedtls_time_t now =
        (mbedtls_time_t)utc_at_open + (mbedtls_time_t)((ubiqos_ticks_now() - ticks_at_open) / 1000u);
    if (timer) *timer = now;
    return now;
}

mbedtls_ms_time_t mbedtls_ms_time(void)
{
    return (mbedtls_ms_time_t)ubiqos_ticks_now();
}

// --- entropy ----------------------------------------------------------------
//
// Raw TRNG samples, eight of them XORed into each byte handed over. They are
// ring-oscillator phase noise and not uniform bits; the fold is conservative,
// and mbedTLS hashes what it is given into its pool before anything is made
// from it.

static int trng_source(void *data, unsigned char *out, size_t len, size_t *olen)
{
    (void)data;
    uint8_t raw[64];
    size_t n = 0;
    while (n < len) {
        const int32_t got = ubiqos_random_trng(raw, sizeof raw);
        if (got < 8) return MBEDTLS_ERR_ENTROPY_SOURCE_FAILED;
        for (int32_t i = 0; i + 8 <= got && n < len; i += 8) {
            uint8_t b = 0;
            for (int k = 0; k < 8; k++) b ^= raw[i + k];
            out[n++] = b;
        }
    }
    *olen = n;
    return 0;
}

// --- the socket, as mbedTLS sees it -----------------------------------------

static int bio_send(void *ctx, const unsigned char *buf, size_t len)
{
    ubiqos_tls_t *t = ctx;
    const int32_t n = ubiqos_sock_send(t->sock, buf, (uint32_t)len);
    if (n < 0) return ERR_SEND_FAILED;
    if (n == 0) return MBEDTLS_ERR_SSL_WANT_WRITE;
    return n;
}

static int bio_recv(void *ctx, unsigned char *buf, size_t len)
{
    ubiqos_tls_t *t = ctx;
    const int32_t n = ubiqos_sock_recv(t->sock, buf, (uint32_t)len);
    if (n < 0) return 0;                      // the peer has gone: end of stream
    if (n == 0) return MBEDTLS_ERR_SSL_WANT_READ;
    return n;
}

// --- roots ------------------------------------------------------------------

static int load_roots(mbedtls_x509_crt *ca)
{
    int loaded = 0;
    uint32_t at = 0;
    // One DER certificate after another: each is a SEQUENCE whose header says
    // how long it is, so the next one starts where that length ends.
    while (at + 4 <= ubiqos_tls_roots_len) {
        const uint8_t *p = ubiqos_tls_roots + at;
        uint32_t len;
        if (p[0] != 0x30) break;
        if (p[1] == 0x82)      len = 4 + (((uint32_t)p[2] << 8) | p[3]);
        else if (p[1] == 0x81) len = 3 + p[2];
        else break;
        if (at + len > ubiqos_tls_roots_len) break;
        if (mbedtls_x509_crt_parse_der(ca, p, len) == 0) loaded++;
        at += len;
    }

    // And whatever the card adds, for a server whose root is not built in.
    uint32_t size = 0;
    if (ubiqos_fs_stat(EXTRA_ROOTS, &size) >= 0 && size > 0 && size < 256u * 1024u) {
        uint8_t *pem = malloc(size + 1);
        const int32_t fd = pem ? ubiqos_open_flags(EXTRA_ROOTS, UBIQOS_O_RDONLY) : -1;
        if (fd >= 0) {
            uint32_t got = 0;
            while (got < size) {
                const int32_t n = ubiqos_read(fd, pem + got, size - got);
                if (n <= 0) break;
                got += (uint32_t)n;
            }
            ubiqos_close(fd);
            pem[got] = 0;
            // Parses every certificate it can and counts the ones it could not;
            // a bad one among good ones is not a reason to lose the good ones.
            if (mbedtls_x509_crt_parse(ca, pem, got + 1) >= 0) loaded++;
        }
        free(pem);
    }
    return loaded;
}

// --- the connection ---------------------------------------------------------

static void say_mbedtls(char *err, size_t cap, const char *what, int ret)
{
    char why[96];
    mbedtls_strerror(ret, why, sizeof why);
    snprintf(err, cap, "%s: %s (-0x%04x)", what, why, (unsigned)-ret);
}

ubiqos_tls_t *ubiqos_tls_open(const char *host, uint16_t port, char *err, size_t errcap)
{
    if (!read_utc(&utc_at_open)) {
        snprintf(err, errcap, "the clock is not set yet, so a certificate's dates "
                              "cannot be checked -- wait for NTP (cat /var/time)");
        return NULL;
    }
    ticks_at_open = ubiqos_ticks_now();
    mbedtls_platform_set_time(tls_time);

    ubiqos_tls_t *t = calloc(1, sizeof *t);
    if (!t) { snprintf(err, errcap, "out of memory"); return NULL; }
    t->sock = -1;
    mbedtls_ssl_init(&t->ssl);
    mbedtls_ssl_config_init(&t->conf);
    mbedtls_x509_crt_init(&t->ca);
    mbedtls_entropy_init(&t->entropy);
    mbedtls_ctr_drbg_init(&t->drbg);

    int ret;
    static const char pers[] = "ubiqos tls client";
    mbedtls_entropy_add_source(&t->entropy, trng_source, NULL, 32, MBEDTLS_ENTROPY_SOURCE_STRONG);
    if ((ret = mbedtls_ctr_drbg_seed(&t->drbg, mbedtls_entropy_func, &t->entropy,
                                     (const unsigned char *)pers, sizeof pers - 1)) != 0) {
        say_mbedtls(err, errcap, "no entropy", ret);
        goto fail;
    }

    if (load_roots(&t->ca) == 0) {
        snprintf(err, errcap, "no root certificates could be loaded");
        goto fail;
    }

    if ((ret = mbedtls_ssl_config_defaults(&t->conf, MBEDTLS_SSL_IS_CLIENT,
                                           MBEDTLS_SSL_TRANSPORT_STREAM,
                                           MBEDTLS_SSL_PRESET_DEFAULT)) != 0) {
        say_mbedtls(err, errcap, "configuring", ret);
        goto fail;
    }
    mbedtls_ssl_conf_authmode(&t->conf, MBEDTLS_SSL_VERIFY_REQUIRED);
    mbedtls_ssl_conf_ca_chain(&t->conf, &t->ca, NULL);
    mbedtls_ssl_conf_rng(&t->conf, mbedtls_ctr_drbg_random, &t->drbg);
    mbedtls_ssl_conf_min_tls_version(&t->conf, MBEDTLS_SSL_VERSION_TLS1_2);
    static const char *alpn[] = { "http/1.1", NULL };
    mbedtls_ssl_conf_alpn_protocols(&t->conf, alpn);

    if ((ret = mbedtls_ssl_setup(&t->ssl, &t->conf)) != 0) {
        say_mbedtls(err, errcap, "setting up", ret);
        goto fail;
    }
    // The name goes out in SNI and is what the certificate must be issued to.
    if ((ret = mbedtls_ssl_set_hostname(&t->ssl, host)) != 0) {
        say_mbedtls(err, errcap, "the host name", ret);
        goto fail;
    }

    t->sock = ubiqos_sock_connect(UBIQOS_NET_LWIP, host, port);
    if (t->sock < 0) { snprintf(err, errcap, "the stack would not start a connection"); goto fail; }
    int32_t st = UBIQOS_TCP_SYN_SENT;
    for (uint32_t waited = 0; waited < CONNECT_MS; waited += SPIN_MS) {
        st = ubiqos_sock_state(t->sock);
        if (st != UBIQOS_TCP_SYN_SENT) break;
        ubiqos_sleep(SPIN_MS);
    }
    if (st != UBIQOS_TCP_ESTABLISHED) {
        snprintf(err, errcap, st == UBIQOS_TCP_SYN_SENT ? "gave up waiting to connect"
                                                        : "could not connect");
        goto fail;
    }
    mbedtls_ssl_set_bio(&t->ssl, t, bio_send, bio_recv, NULL);

    const uint32_t start = ubiqos_ticks_now();
    while ((ret = mbedtls_ssl_handshake(&t->ssl)) != 0) {
        if (ret != MBEDTLS_ERR_SSL_WANT_READ && ret != MBEDTLS_ERR_SSL_WANT_WRITE) {
            const uint32_t flags = mbedtls_ssl_get_verify_result(&t->ssl);
            if (ret == MBEDTLS_ERR_X509_CERT_VERIFY_FAILED && flags) {
                char why[160];
                mbedtls_x509_crt_verify_info(why, sizeof why, "", flags);
                size_t n = strlen(why);
                while (n && (why[n - 1] == '\n' || why[n - 1] == ' ')) why[--n] = 0;
                snprintf(err, errcap, "the certificate was refused: %s", why);
            } else {
                say_mbedtls(err, errcap, "the handshake failed", ret);
            }
            goto fail;
        }
        if (ubiqos_ticks_now() - start > HANDSHAKE_MS) {
            snprintf(err, errcap, "the handshake took too long");
            goto fail;
        }
        ubiqos_sleep(SPIN_MS);
    }
    return t;

fail:
    if (t->sock >= 0) { ubiqos_sock_close(t->sock); t->sock = -1; }
    ubiqos_tls_close(t);
    return NULL;
}

int32_t ubiqos_tls_write(ubiqos_tls_t *t, const void *buf, uint32_t len)
{
    const unsigned char *p = buf;
    uint32_t done = 0;
    while (done < len) {
        const int r = mbedtls_ssl_write(&t->ssl, p + done, len - done);
        if (r > 0) { done += (uint32_t)r; continue; }
        if (r == MBEDTLS_ERR_SSL_WANT_READ || r == MBEDTLS_ERR_SSL_WANT_WRITE) {
            ubiqos_sleep(SPIN_MS);
            continue;
        }
        return -1;
    }
    return (int32_t)done;
}

int32_t ubiqos_tls_read(ubiqos_tls_t *t, void *buf, uint32_t len, uint32_t timeout_ms)
{
    const uint32_t start = ubiqos_ticks_now();
    for (;;) {
        const int r = mbedtls_ssl_read(&t->ssl, buf, len);
        if (r > 0) return r;
        // A server that closes without saying so is common, and what it sent
        // before that is still whole: each record was checked as it came.
        if (r == 0 || r == MBEDTLS_ERR_SSL_PEER_CLOSE_NOTIFY || r == MBEDTLS_ERR_SSL_CONN_EOF)
            return 0;
        if (r != MBEDTLS_ERR_SSL_WANT_READ && r != MBEDTLS_ERR_SSL_WANT_WRITE)
            return -1;
        if (ubiqos_ticks_now() - start > timeout_ms) return -2;
        ubiqos_sleep(SPIN_MS);
    }
}

const char *ubiqos_tls_cipher(ubiqos_tls_t *t)
{
    return t ? mbedtls_ssl_get_ciphersuite(&t->ssl) : "";
}

void ubiqos_tls_close(ubiqos_tls_t *t)
{
    if (!t) return;
    if (t->sock >= 0) {
        mbedtls_ssl_close_notify(&t->ssl);    // once; a peer already gone is fine
        ubiqos_sock_close(t->sock);
    }
    mbedtls_ssl_free(&t->ssl);
    mbedtls_ssl_config_free(&t->conf);
    mbedtls_x509_crt_free(&t->ca);
    mbedtls_ctr_drbg_free(&t->drbg);
    mbedtls_entropy_free(&t->entropy);
    free(t);
}
