#!/usr/bin/env python3
"""Embed a built .mod file in the kernel image as a C array.

QEMU placed the module at a fixed address with -device loader. On hardware there
is no such thing, so the module rides along in flash. The shape is the same
either way: the kernel gets a pointer to a module header and does not care where
det kom.
"""
import sys

src, dst, symbol = sys.argv[1], sys.argv[2], sys.argv[3]
data = open(src, "rb").read()

with open(dst, "w") as f:
    f.write("// Generated by make_blob.py. Do not edit.\n")
    f.write("#include <stdint.h>\n\n")
# 4-byte aligned: the module header is read as 32-bit words.
    f.write(f"__attribute__((aligned(4))) const uint8_t {symbol}[] = {{\n")
    for i in range(0, len(data), 12):
        row = ", ".join(f"0x{b:02x}" for b in data[i:i + 12])
        f.write(f"    {row},\n")
    f.write("};\n")
    f.write(f"const uint32_t {symbol}_size = {len(data)};\n")

print(f"  {dst}: {len(data)} byte som {symbol}")
