#!/usr/bin/env python3
"""Rasterise a monospace outline font into the kernel's 8x16 bitmap table.

The table is baked into the kernel image, so it inherits the typeface's licence
and the typeface must be one that may be redistributed. JuliaMono is SIL OFL 1.1;
its licence travels with us in docs/fonts/OFL-JuliaMono.txt.

Beware fonts installed by Creative Cloud: the Source Code Pro on this machine
carries Adobe's proprietary notice in its name table even though the project's
own GitHub release is OFL. Check name ID 13 before trusting a font, which is what
--check prints.
"""
import sys
from PIL import Image, ImageDraw, ImageFont

FONT      = "JuliaMono-Regular.ttf"
SIZE      = 13
THRESHOLD = 130
BASELINE  = 13
OUT       = "kernel/font8x16.c"


def licence_of(path):
    from fontTools.ttLib import TTFont
    names = {r.nameID: r.toUnicode() for r in TTFont(path).name.names if r.platformID == 3}
    return names.get(0, "?"), names.get(13, "?"), names.get(14, "?")


def render(font, cp):
    img = Image.new("L", (8, 16), 0)
    ImageDraw.Draw(img).text((0, BASELINE), chr(cp), font=font, fill=255, anchor="ls")
    return [sum(0x80 >> x for x in range(8) if img.getpixel((x, y)) > THRESHOLD)
            for y in range(16)]


def main():
    font = ImageFont.truetype(FONT, SIZE)
    if "--check" in sys.argv:
        for field in licence_of(font.path):
            print(field)
        return
    if "--preview" in sys.argv:
        for ch in "AmgW1#@":
            print(ch)
            for row in render(font, ord(ch)):
                print("  " + "".join("#" if row & (0x80 >> i) else "." for i in range(8)))
        return

    glyphs = [render(font, cp) for cp in range(32, 127)]
    with open(OUT, "w") as f:
        f.write(HEADER)
        for cp, rows in zip(range(32, 127), glyphs):
            f.write("    {%s},  // %d\n" % (",".join("0x%02x" % b for b in rows), cp))
        f.write("};\n")
    print("wrote %s, %d glyphs" % (OUT, len(glyphs)))


HEADER = '''// An 8x16 fixed-width font covering ASCII 32..126, one byte per scanline with
// the most significant bit leftmost, sixteen bytes per glyph.
//
// Rasterised from JuliaMono Regular at 13 px. The table is baked into the kernel
// image and so inherits the typeface's licence:
//
//   Copyright (c) 2020 - 2023, cormullion, with Reserved Font Name JuliaMono.
//   SIL Open Font License 1.1 -- see docs/fonts/OFL-JuliaMono.txt
//
// This file is generated by tools/make_font.py. Edit the generator, not the
// table.
#include <stdint.h>

const uint8_t myrtos_font8x16[95][16] = {
'''

main()
