#!/usr/bin/env python3
"""Write modules/tlsroots/tlsroots.c: the root certificates a TLS client trusts.

usage: tools/make_roots.py            (on macOS; reads the system trust store)

The roots are taken from macOS's own list of trusted roots, and each one is
pinned here by its SHA-256 fingerprint: a root that is not there, or not the
one named, stops the script rather than slipping into the build. The list is
the issuers behind most of the web and the large clouds -- Let's Encrypt,
DigiCert, Google Trust Services, GlobalSign, Amazon, Sectigo (USERTrust),
Microsoft, SSL.com (which Cloudflare issues under) and GoDaddy/Starfield. A
server whose root is not here can still be reached by putting its root in
/sd/certs.pem.

The output is the source of the tlsroots data module: a small header -- see
lib/tls/ubiqos_tls_roots.h -- and then one DER certificate after another, which
the client walks by the length in each certificate's own header. After a
change here, raise the module's REV in CMakeLists.txt: a newer revision put on
a card replaces the one in flash, which is how a system in the field gets new
roots without being rebuilt.
"""
import hashlib, os, subprocess, sys

KEYCHAIN = "/System/Library/Keychains/SystemRootCertificates.keychain"

ROOTS = [
    ("ISRG Root X1",                                   "96BCEC06264976F37460779ACF28C5A7CFE8A3C0AAE11A8FFCEE05C0BDDF08C6"),
    ("ISRG Root X2",                                   "69729B8E15A86EFC177A57AFB7171DFC64ADD28C2FCA8CF1507E34453CCB1470"),
    ("DigiCert Global Root CA",                        "4348A0E9444C78CB265E058D5E8944B4D84F9662BD26DB257F8934A443C70161"),
    ("DigiCert Global Root G2",                        "CB3CCBB76031E5E0138F8DD39A23F9DE47FFC35E43C1144CEA27D46A5AB1CB5F"),
    ("DigiCert Global Root G3",                        "31AD6648F8104138C738F39EA4320133393E3A18CC02296EF97C2AC9EF6731D0"),
    ("GTS Root R1",                                    "D947432ABDE7B7FA90FC2E6B59101B1280E0E1C7E4E40FA3C6887FFF57A7F4CF"),
    ("GTS Root R4",                                    "349DFA4058C5E263123B398AE795573C4E1313C83FE68F93556CD5E8031B3C7D"),
    ("GlobalSign Root CA",                             "EBD41040E4BB3EC742C9E381D31EF2A41A48B6685C96E7CEF3C1DF6CD4331C99"),
    ("Amazon Root CA 1",                               "8ECDE6884F3D87B1125BA31AC3FCB13D7016DE7F57CC904FE1CB97C6AE98196E"),
    ("Amazon Root CA 3",                               "18CE6CFE7BF14E60B2E347B8DFE868CB31D02EBB3ADA271569F50343B46DB3A4"),
    ("USERTrust RSA Certification Authority",          "E793C9B02FD8AA13E21C31228ACCB08119643B749C898964B1746D46C3D4CBD2"),
    ("USERTrust ECC Certification Authority",          "4FF460D54B9C86DABFBCFC5712E0400D2BED3FBC4D4FBDAA86E06ADCD2A9AD7A"),
    ("Microsoft RSA Root Certificate Authority 2017",  "C741F70F4B2A8D88BF2E71C14122EF53EF10EBA0CFA5E64CFA20F418853073E0"),
    ("Microsoft ECC Root Certificate Authority 2017",  "358DF39D764AF9E1B766E9C972DF352EE15CFAC227AF6AD1D70E8E4A6EDCBA02"),
    ("SSL.com TLS ECC Root CA 2022",                   "C32FFD9F46F936D16C3673990959434B9AD60AAFBB9E7CF33654F144CC1BA143"),
    ("SSL.com TLS RSA Root CA 2022",                   "8FAF7D2E2CB4709BB8E0B33666BF75A5DD45B5DE480F8EA8D4BFE6BEBC17F2ED"),
    ("SSL.com Root Certification Authority ECC",       "3417BB06CC6007DA1B961C920B8AB4CE3FAD820E4AA30B9ACBC4A74EBDCEBC65"),
    ("SSL.com Root Certification Authority RSA",       "85666A562EE0BE5CE925C1D8890A6F76A87EC16D4D7D5F29EA7419CF20123B69"),
    ("Go Daddy Root Certificate Authority - G2",       "45140B3247EB9CC8C5B4F0D7B53091F73292089E6E5A63E2749DD3ACA9198EDA"),
    ("Starfield Services Root Certificate Authority - G2",
                                                       "568D6905A2C88708A4B3025190EDCFEDB1974A606A13C6E5290FCB2AE63EDAB5"),
]


def der_of(name, fingerprint):
    # -c matches a substring, so several may come back; the fingerprint picks.
    pem = subprocess.run(["security", "find-certificate", "-a", "-c", name, "-p", KEYCHAIN],
                         capture_output=True, text=True, check=True).stdout
    for block in pem.split("-----END CERTIFICATE-----"):
        if "-----BEGIN CERTIFICATE-----" not in block:
            continue
        block += "-----END CERTIFICATE-----\n"
        der = subprocess.run(["openssl", "x509", "-outform", "DER"], input=block.encode(),
                             capture_output=True, check=True).stdout
        if hashlib.sha256(der).hexdigest().upper() == fingerprint:
            return der
    sys.exit(f"make_roots: {name}: no certificate with the pinned fingerprint")


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    out = os.path.join(here, "..", "modules", "tlsroots", "tlsroots.c")
    blob, index = b"", []
    for name, fp in ROOTS:
        der = der_of(name, fp)
        index.append((name, fp, len(der)))
        blob += der
    lines = [
        "// GENERATED by tools/make_roots.py -- edit the list there, not this file,",
        "// and raise tlsroots' REV in CMakeLists.txt when it changes.",
        "//",
        "// The root certificates a TLS client trusts, as the tlsroots data module:",
        "// the header in lib/tls/ubiqos_tls_roots.h, then DER, one after another.",
        "// Each is pinned in the script by its SHA-256 fingerprint:",
        "//",
    ]
    for name, fp, n in index:
        lines.append(f"//   {name} ({n} bytes)")
        lines.append(f"//     {fp}")
    lines += ["",
              "#include <stdint.h>",
              "",
              "typedef struct {",
              "    char     magic[8];",
              "    uint32_t count;",
              "    uint32_t length;",
              f"    uint8_t  der[{len(blob)}];",
              "} roots_t;",
              "",
              "__attribute__((section(\".rodata.descriptor\"), used))",
              "const roots_t tlsroots = {",
              "    { 'U', 'B', 'Q', 'R', 'O', 'O', 'T', 'S' },",
              f"    {len(index)},",
              f"    {len(blob)},",
              "    {"]
    for k in range(0, len(blob), 16):
        lines.append("        " + ", ".join(f"0x{b:02x}" for b in blob[k:k + 16]) + ",")
    lines += ["    },", "};", ""]
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w") as f:
        f.write("\n".join(lines))
    print(f"{out}: {len(index)} roots, {len(blob)} bytes")


if __name__ == "__main__":
    main()
