#!/usr/bin/env python3
"""Generate the polyphase resampler's coefficients for modules/play.

A Kaiser-windowed sinc, sampled NPHASE times between each pair of zero
crossings and NZERO crossings out from the centre. Written as a table rather
than computed on the board because a module has neither floating point -- the
RISC-V half of this system has no FPU and no libgcc to fake one -- nor libm to
ask for a sine.

The table is one half of a symmetric impulse response: h[0] is the centre and
h[NZERO*NPHASE] is the last zero. The resampler reads it in both directions.

    python3 tools/make_sinc.py > modules/play/sinc_table.h
"""
import math

NZERO  = 10      # zero crossings each side of the centre: 20 taps at unity rate
NPHASE = 64      # samples between crossings; the fraction interpolates between
CUTOFF = 0.475   # of the input Nyquist, leaving the top 5% as transition band
BETA   = 8.0     # Kaiser beta; about 74 dB of stopband at this length

def i0(x):
    """Modified Bessel function of the first kind, order zero."""
    s, t, k = 1.0, 1.0, 1
    while t > 1e-16 * s:
        t *= (x / (2.0 * k)) ** 2
        s += t
        k += 1
    return s

n = NZERO * NPHASE
h = []
for i in range(n + 1):
    t = i / NPHASE                                  # in zero crossings
    # sinc(2*cutoff*t), which is the ideal low-pass at that cutoff
    sinc = 2.0 * CUTOFF if i == 0 else math.sin(2 * math.pi * CUTOFF * t) / (math.pi * t)
    r = i / n
    win = i0(BETA * math.sqrt(max(0.0, 1.0 - r * r))) / i0(BETA)
    h.append(sinc * win)

# Normalise so that a run of identical samples comes back at the same level:
# the sum of every NPHASE-th coefficient, both wings, is the DC gain.
dc = h[0] + 2.0 * sum(h[k] for k in range(NPHASE, n + 1, NPHASE))
h = [v / dc for v in h]

scale = 32767
q = [max(-32768, min(32767, int(round(v * scale)))) for v in h]

print("// Generated by tools/make_sinc.py -- do not edit.")
print("//")
print(f"// Kaiser-windowed sinc, beta {BETA}, cutoff {CUTOFF} of the input Nyquist,")
print(f"// {NZERO} zero crossings each side sampled {NPHASE} times between each pair.")
print("// Q15, half the response; h[0] is the centre and the rest is symmetric.")
print()
print(f"#define SINC_NZERO  {NZERO}")
print(f"#define SINC_NPHASE {NPHASE}")
print()
print(f"static const int16_t sinc_h[{n + 1}] = {{")
for i in range(0, n + 1, 12):
    print("    " + ", ".join("%6d" % v for v in q[i:i+12]) + ",")
print("};")
