#!/usr/bin/env python3
"""Convert Terminus into the kernel's font tables.

Terminus is a bitmap font: every glyph was drawn by hand on each of these grids.
That is why it looks right at eight pixels wide and the outline fonts did not --
rasterising a curve into an 8x16 cell forces the rasteriser to guess where the
stems land, and it guesses differently for every letter. The 6x12 is not the
16 scaled down; it is its own drawing, which is why it stays readable.

The tables are baked into the kernel image and so inherit the typeface's
licence. Terminus is SIL OFL 1.1; the licence and the source .bdf files travel
with us in third_party/terminus. Beware fonts installed by a font manager: the
Source Code Pro on this machine carries Adobe's proprietary notice in its name
table even though the upstream project releases it under the OFL.

Both tables come out in the same shape -- one byte per scanline, leftmost pixel
in bit 7 -- so the console can draw either without knowing which it has. A six
pixel cell therefore leaves bits 1 and 0 unused rather than sitting right
aligned, which would have made every glyph a special case.

  python3 tools/make_font.py                regenerate both tables
  python3 tools/make_font.py --preview 6x12 print a few glyphs as text
"""
import sys

FIRST, LAST = 32, 255

FONTS = [
    # name    bdf                                     w   h
    ("8x16", "third_party/terminus/ter-u16n.bdf", 8, 16),
    ("6x12", "third_party/terminus/ter-u12n.bdf", 6, 12),
]


def read_bdf(path):
    """Return {codepoint: (bbx, [hex rows])} and the font bounding box."""
    lines = open(path, encoding="latin-1").read().splitlines()
    fbb, glyphs, i = None, {}, 0
    while i < len(lines):
        if lines[i].startswith("FONTBOUNDINGBOX"):
            fbb = [int(v) for v in lines[i].split()[1:]]
        elif lines[i].startswith("STARTCHAR"):
            enc = bbx = None
            bits = []
            while not lines[i].startswith("ENDCHAR"):
                if lines[i].startswith("ENCODING"):
                    enc = int(lines[i].split()[1])
                elif lines[i].startswith("BBX"):
                    bbx = [int(v) for v in lines[i].split()[1:]]
                elif lines[i].startswith("BITMAP"):
                    j = i + 1
                    while not lines[j].startswith("ENDCHAR"):
                        bits.append(lines[j].strip())
                        j += 1
                    i = j - 1
                i += 1
            if enc is not None:
                glyphs[enc] = (bbx, bits)
        i += 1
    return fbb, glyphs


def to_cell(fbb, glyphs, cp, cell_w, cell_h):
    """Place one glyph into the cell, honouring its bounding-box offsets."""
    rows = [0] * cell_h
    if cp not in glyphs:
        return rows
    (w, h, xoff, yoff), bits = glyphs[cp]
    _, fh, fx, fy = fbb
    top = fh - (yoff - fy) - h
    for k, hexrow in enumerate(bits):
        v = int(hexrow, 16)
        v >>= max(0, len(hexrow) * 4 - w)      # right-align the glyph's own bits
        v <<= max(0, cell_w - w - xoff + fx)   # then place it in the cell
        v &= (1 << cell_w) - 1
        v <<= 8 - cell_w                       # and left-align the cell in a byte
        y = top + k
        if 0 <= y < cell_h:
            rows[y] = v & 0xFF
    return rows


HEADER = '''// A %(name)s fixed-width font covering 32..255 -- ASCII and Latin-1 -- one byte
// per scanline with the leftmost pixel in bit 7, %(h)d bytes per glyph. A cell
// narrower than eight pixels leaves the low bits clear.
//
// Latin-1 rather than ASCII because a keyboard layout is no use without the
// letters it produces: a Swedish one gives a, a and o with their marks, and
// there has to be something to draw.
//
// Terminus, a bitmap font drawn by hand on this exact grid. The table is baked
// into the kernel image and so inherits the typeface's licence:
//
//   Copyright (C) 2020 Dimitar Toshkov Zhekov,
//   with Reserved Font Name "Terminus Font".
//   SIL Open Font License 1.1 -- see third_party/terminus/OFL.txt
//
// This file is generated by tools/make_font.py. Edit the generator, not the
// table.
//
// In flash, not in RAM. The kernel is linked copy_to_ram, which pulls anything
// not marked .flashdata into RAM "to avoid accidental flash accesses" as the
// SDK's own linker script puts it -- and six kilobytes of glyphs in a machine
// whose framebuffer already takes three hundred is six kilobytes that a process
// does not get. The accident the SDK warns about cannot happen here: nothing
// writes flash while ubiqos is running, so reading it is always safe.
#include <stdint.h>

__attribute__((section(".flashdata.font%(name)s")))
const uint8_t ubiqos_font%(name)s[224][%(h)d] = {
'''


def main():
    want = None
    if "--preview" in sys.argv:
        i = sys.argv.index("--preview")
        want = sys.argv[i + 1] if len(sys.argv) > i + 1 else "8x16"

    for name, bdf, cell_w, cell_h in FONTS:
        fbb, glyphs = read_bdf(bdf)
        if want is not None:
            if name != want:
                continue
            for ch in "AmgW1#@åäö":
                print(ch)
                for row in to_cell(fbb, glyphs, ord(ch), cell_w, cell_h):
                    print("  " + "".join("#" if row & (0x80 >> i) else "."
                                         for i in range(cell_w)))
            return
        out = "kernel/font%s.c" % name
        with open(out, "w") as f:
            f.write(HEADER % {"name": name, "h": cell_h})
            for cp in range(FIRST, LAST + 1):
                rows = to_cell(fbb, glyphs, cp, cell_w, cell_h)
                f.write("    {%s},  // %d\n" % (",".join("0x%02x" % b for b in rows), cp))
            f.write("};\n")
        print("wrote %s, %d glyphs from %s" % (out, LAST - FIRST + 1, bdf))


main()
